version: "3.9"
services:
  prediction-service:
    image: babkin/prediction-service

    build:
      context: ./app
      dockerfile: Dockerfile

    ports:
        - "8080:8080"

    volumes:
        - ${PWD}/app/models:/app/models

    networks:
      - app

networks:
  app:
